# Generated by Django 3.1.12 on 2023-05-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('clp', 'Pesos'), ('usd', 'Dólares')], default='clp', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='currency_exchange',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='usd_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.IntegerField(),
        ),
    ]
