# Generated by Django 4.2.1 on 2023-05-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_currency_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tom_bank_id',
            field=models.CharField(default='', max_length=36),
            preserve_default=False,
        ),
    ]
